// SPDX-License-Identifier: GPL-2.0-or-later
pub mod contracts;
pub mod core;
pub mod error;
pub mod league;
pub mod library;
pub mod media;
pub mod paths;
pub mod process;
pub mod recorder;
pub use core::Core;
pub use error::{Error,Result};
