// Generated by cargo run -p playz-core --bin generate-contracts. Do not edit.
export type Phase = "idle" | "preparing" | "recording" | "finalizing" | "ready" | "interrupted" | "failed";
export type Settings = { schema_version: number, recording_folder: string, capture_kind: string, target_id: string, target_label: string, encoder_id: string, width: number, height: number, fps: number, bitrate_kbps: number, desktop_audio: boolean, audio_output_id: string, microphone_id: string, hotkey_record: string, hotkey_bookmark: string, hide_to_tray: boolean, theme: string, reserve_gib: number, };
export type Choice = { id: string, label: string, };
export type CaptureTarget = { id: string, label: string, kind: string, };
export type Encoder = { id: string, label: string, hardware: boolean, hardware_validated: boolean, };
export type Capabilities = { protocol: number, engine_version: string, targets: Array<CaptureTarget>, encoders: Array<Encoder>, audio_outputs: Array<Choice>, audio_inputs: Array<Choice>, };
export type Snapshot = { phase: Phase, recording_id: string | null, elapsed_ms: number, written_bytes: string, free_bytes: string, error: string | null, capture_warning: string | null, engine_connected: boolean, settings: Settings, };
export type Recording = { id: string, title: string, created_at: string, phase: Phase, duration_ms: number, bytes: string, favorite: boolean, tags: Array<string>, notes: string, source_label: string, capture_kind: string, has_playback: boolean, resume_ms: number, error: string | null, };
export type LibraryPage = { items: Array<Recording>, total: number, };
export type Details = { title: string, favorite: boolean, tags: Array<string>, notes: string, };
export type Bookmark = { id: string, recording_id: string, position_ms: number, label: string, note: string, };
export type ExportMode = "accurate" | "fast";
export type ExportRequest = { recording_id: string, start_ms: number, end_ms: number, mode: ExportMode, name: string, };
export type ExportJob = { id: string, recording_id: string, state: string, mode: ExportMode, start_ms: number, end_ms: number, name: string, progress: number, error: string | null, };
export type Diagnostic = { name: string, status: string, detail: string, };
