// SPDX-License-Identifier: GPL-2.0-or-later
import { useQuery } from '@tanstack/react-query';
import { FolderOpen, RefreshCw, X, Database, ShieldCheck } from 'lucide-react';
import { api } from '../lib/api';
import { useAction } from '../lib/hooks';
import { duration } from '../lib/format';
import { Button, Empty, Feedback, PageTitle } from '../components/ui';

export function ExportsView({ busy }: { busy: boolean }) {
  const action = useAction();
  const jobs = useQuery({ queryKey: ['exports'], queryFn: api.exports, refetchInterval: 1000 });
  return <><PageTitle eyebrow="BACKGROUND MEDIA JOBS" title="Export queue">Original files stay intact. Finished clips are validated before they are published to disk.</PageTitle><Feedback error={jobs.error || action.error} message={action.message}/>{busy && <div className="notice warning">Encoding pauses while recording or finalizing. Paused exports restart from trim-in afterward; they do not resume from an encoded byte offset.</div>}{jobs.isPending && <p role="status">Reading export jobs…</p>}{jobs.data?.length === 0 && <Empty title="No exports queued"><p>Open a recording, select your trim interval and choose Queue export.</p></Empty>}<div className="job-list">{jobs.data?.map(job => <article className="panel job" key={job.id}><div className="row between"><div><h2>{job.name}</h2><p className="muted">{duration(job.start_ms)} → {duration(job.end_ms)} · {job.mode === 'accurate' ? 'H.264 / AAC re-encode' : 'Keyframe-aligned stream copy'}</p></div><span className={`phase-tag phase-${job.state}`}>{busy && job.state === 'queued' ? 'Waiting for capture' : job.state}</span></div><progress max={100} value={job.progress} aria-label={`Export progress for ${job.name}`}/><div className="row between"><span className="mono small">{Math.round(job.progress)}%</span><div className="row">{['running', 'queued'].includes(job.state) && <Button busy={action.pending} onClick={() => void action.run(() => api.cancel(job.id))}><X size={16}/>Cancel</Button>}{['failed', 'cancelled'].includes(job.state) && <Button busy={action.pending} onClick={() => void action.run(() => api.retry(job.id))}><RefreshCw size={16}/>Retry</Button>}{job.state === 'completed' && <Button onClick={() => void action.run(() => api.revealExport(job.id))}><FolderOpen size={16}/>Show clip</Button>}</div></div>{job.error && <p className={job.state === 'failed' ? 'field-error' : 'muted small'}>{job.error}</p>}</article>)}</div></>;
}
export function DiagnosticsView() {
  const action = useAction();
  const diagnostics = useQuery({ queryKey: ['diagnostics'], queryFn: api.diagnostics, refetchInterval: 5000 });
  return <><PageTitle eyebrow="LOCAL SYSTEM STATUS" title="Diagnostics" actions={<Button busy={diagnostics.isFetching} onClick={() => void diagnostics.refetch()}><RefreshCw size={17}/>Refresh</Button>}>Presence checks are not proof of successful capture. Validate your first recording on this computer.</PageTitle><Feedback error={diagnostics.error || action.error} message={action.message}/><div className="diagnostic-list">{diagnostics.data?.map(d => <section className="panel diagnostic" key={d.name}><div className="row between"><h2>{d.name}</h2><span className={`phase-tag phase-${d.status}`}>{d.status.replaceAll('_', ' ')}</span></div><p className="muted">{d.detail}</p></section>)}</div><section className="panel"><h2><Database size={18}/>Consistent library backup</h2><p>Back up the SQLite catalog through its backup API. Video masters and playback files are separate; this action does not copy them.</p><Button busy={action.pending} onClick={() => void action.run(async () => { const result = await api.backup(); return result; }, 'Consistent local catalog backup created and shown in Explorer. Copy video folders separately.')}><Database size={17}/>Create catalog backup</Button></section><section className="panel"><h2><ShieldCheck size={18}/>Troubleshooting without uploading your files</h2><p>For interrupted capture, preserve the master and use Recover in Match review. For a missing drive, reconnect it or use Relink. For capture errors, refresh devices and explicitly choose the same game/window again.</p><p className="muted">No diagnostics are sent anywhere. Review any information before manually sharing it. Signing, real Windows 11 installation and sustained GPU capture evidence are tracked in the repository release checklist.</p></section></>;
}
